sudo: false
language: rust
rust: nightly

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.3
      before_install:
        - rustup self uninstall
        - curl https://sh.rustup.rs -sSf | sh
        - rustup install nightly

script:
  - cargo build --release
cache: cargo
branches:
  only:
    - master
